---

- name: Check if variables are defined
  ansible.builtin.assert:
    that:
      - admins is truthy

- name: Ensure group "managed" exists
  ansible.builtin.group:
    name: managed
    state: present

- name: Ensure sudo is installed
  ansible.builtin.package:
    name: sudo

- name: Create admin users
  ansible.builtin.user:
    name: '{{ item.name }}'
    groups: managed
    append: true
  loop: '{{ admins | flatten }}'
  loop_control:
    label: '{{ item.name }}'

- name: Allow users to sudo without password
  ansible.builtin.copy:
    owner: root
    group: root
    mode: '0644'
    dest: /etc/sudoers.d/99-user_setup-{{ item.name }}
    content: '{{ item.name }} ALL=(ALL) NOPASSWD: ALL'
  loop: '{{ admins | flatten }}'
  loop_control:
    label: '{{ item.name }}'

- name: Set up admin authorized keys
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    state: present
    exclusive: true
    key: >
      {{
      lookup('ansible.builtin.url', item.key, split_lines=False)
      if item.key.startswith('http') else
      lookup('ansible.builtin.file', item.key.split(':', 1)[1])
      if item.key.startswith('file:') else
      item.key
      }}
  loop: '{{ admins | flatten }}'
  loop_control:
    label: '{{ item.name }}'

- name: Detect and remove old users
  when: user_setup_delete_users
  block:
    - name: Get all managed users
      ansible.builtin.command:  # noqa command-instead-of-module
        cmd: sed -n s/^managed:.*://p /etc/group
      register: managed_users
      changed_when: false

    - name: Calculate old users
      ansible.builtin.set_fact:
        old_users: >
          {{ managed_users.stdout.split(",")
          | difference((admins | flatten | map(attribute="name"))) }}
      delegate_to: 127.0.0.1
      become: false

    - name: Remove old users from sudoers
      ansible.builtin.file:
        state: absent
        path: /etc/sudoers.d/99-user_setup-{{ item }}
      loop: '{{ old_users }}'

    - name: Remove old users
      ansible.builtin.user:
        name: '{{ item }}'
        state: absent
        remove: true
      loop: '{{ old_users }}'

    - name: Delete old home directories
      ansible.builtin.file:
        state: absent
        path: /home/{{ item }}/
      loop: '{{ old_users }}'
