---
- name: Check if variables are defined
  ansible.builtin.assert:
    that:
      - admins is truthy

- name: Ensure sudo is installed
  ansible.builtin.package:
    name: sudo

- name: Create admin users
  ansible.builtin.user:
    name: "{{ item.name }}"
    append: true
  loop: "{{ admins | flatten }}"

- name: Allow users to sudo without password
  ansible.builtin.copy:
    owner: root
    group: root
    mode: '0644'
    dest: /etc/sudoers.d/99-user_setup-{{ item.name }}
    content: '{{ item.name }} ALL=(ALL) NOPASSWD: ALL'
  loop: "{{ admins | flatten }}"

- name: Set up admin authorized keys
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    state: present
    exclusive: true
    key: >
      {{
      lookup('ansible.builtin.url', item.key, split_lines=False)
      if item.key.startswith('http')
      lookup('ansible.builtin.file', item.key)
      }}
  loop: "{{ admins | flatten }}"

- name: Detect and remove old users
  when: delete_users
  block:
    - name: Detect users
      ansible.builtin.find:
        paths: /home/
        recurse: false
        file_type: directory
      register: system_users

    - name: Detect old users
      ansible.builtin.set_fact:
        old_users: >
          {{ system_users.files
          | map(attribute="pw_name")
          | difference((admins + [{"name":"root"}]) | flatten) }}
      delegate_to: 127.0.0.1
      become: false

    - name: Remove old users from sudoers
      ansible.builtin.file:
        state: absent
        path: /etc/sudoers.d/99-user_setup-{{ item.name }}
      loop: '{{ old_users }}'

    - name: Remove old users
      ansible.builtin.user:
        name: '{{ item }}'
        state: absent
        remove: true
      loop: '{{ old_users }}'

    - name: Delete old home directories
      ansible.builtin.file:
        state: absent
        path: /home/{{ item }}/
      loop: '{{ old_users }}'
