---
- name: Test Deployment
  hosts: all
  become: true
  vars:
    global_admins: &adm
      # yamllint disable rule:line-length
      - name: ftest
        key: file:.test.pub
      - name: utest
        key: https://gitlab.uni-osnabrueck.de/virtuos/digitale-dienste/ssh-keys/-/raw/main/lars.pub
  roles:
    - role: user_setup
      user_setup_delete_users: true
      user_setup_admins:
        - *adm
        - name: ktest
          key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJD6IefLuRrBMPvXv7PVj0nIwHZIv1r/LSNRIien9dke
